version: "3.9"
services:
  server:
    container_name: store_backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      DB_NAME: postgres1
      DB_USER: postgres1
      DB_PASSWORD: postgres1
      DB_HOST: postgres
      DB_PORT: 5432

  postgres:
    container_name: store_bd
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: postgres1

  client:
    container_name: store_client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    volumes:
      - ".:/client"
      - "/client/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://0.0.0.0:5000/
